name: Build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 -> Code Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Step 2 -> Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Step 3 -> Setup Node JS
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Step 4 -> Install packages
        run: pnpm install --frozen-lockfile
      - name: Step 5 -> Run Tests & Generate Coverage Report
        run: pnpm run test:cov
      - name: Step 6 -> Upload Coverage Report
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}